
services:
  cms-db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cms_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  cms-app:
    build: .
    command: sh -c "sleep 10 && node dist/index.js"
    ports:
      - "3000:3000"
    environment:
      DB_HOST: cms-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: cms_dev
      JWT_SECRET: your_strong_jwt_secret_here
    depends_on:
      - cms-db
    restart: on-failure:5

volumes:
  pgdata: